# Schema for the configuration files of the Static Metadata Records module.
static_metadata_records.settings:
  type: config_object
  label: 'Static Metadata Records settings'
  mapping:
    example:
      type: string
      label: 'Example'
